#!/usr/bin/env node
/**
 * Generates the third-party notices of what ships inside the window:
 * `third-party/npm.md` (production npm tree) and `third-party/rust.md`
 * (normal Rust dependencies of `terminus`, every target platform).
 *
 *   node scripts/notices.mjs
 *
 * Needs `pnpm install` and the Cargo registry sources (`cargo fetch`). Identical
 * license texts are printed once with every package that carries them.
 */
import { execFileSync, execSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "third-party");
const LICENSE_FILE = /^(licen[cs]e|copying|notice|copyright)([-._].*)?$/i;

function licenseTexts(dir) {
  if (!dir || !existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((name) => LICENSE_FILE.test(name))
    .sort()
    .map((name) => readFileSync(join(dir, name), "utf8").replace(/\r\n/g, "\n").trim())
    .filter(Boolean);
}

function render(title, intro, packages) {
  const byText = new Map();
  const missing = [];
  for (const p of packages) {
    if (!p.texts.length) {
      missing.push(p);
      continue;
    }
    const key = p.texts.join("\n\n---\n\n");
    if (!byText.has(key)) byText.set(key, []);
    byText.get(key).push(p);
  }
  const lines = [`# ${title}`, "", intro, "", `Generated by \`node scripts/notices.mjs\`. ${packages.length} packages.`, ""];
  lines.push("## Packages", "", "| Package | Version | License | Source |", "|---|---|---|---|");
  for (const p of packages) lines.push(`| ${p.name} | ${p.version} | ${p.license || "see source"} | ${p.source || ""} |`);
  lines.push("", "## License texts", "");
  for (const [text, group] of byText) {
    lines.push(`### ${group.map((p) => `${p.name} ${p.version}`).join(", ")}`, "", "```text", text.replaceAll("```", "'''"), "```", "");
  }
  if (missing.length) {
    lines.push("## Packages without a license file in their distribution", "");
    for (const p of missing) lines.push(`- ${p.name} ${p.version} — ${p.license || "no license declared"} ${p.source || ""}`);
    lines.push("");
  }
  return `${lines.join("\n")}\n`;
}

function npmPackages() {
  const json = JSON.parse(execSync("pnpm licenses list --prod --json", { cwd: ROOT, encoding: "utf8", maxBuffer: 64 << 20 }));
  const packages = [];
  for (const [license, entries] of Object.entries(json)) {
    for (const entry of entries) {
      entry.versions.forEach((version, i) => {
        packages.push({ name: entry.name, version, license, source: entry.homepage ?? "", texts: licenseTexts(entry.paths[i]) });
      });
    }
  }
  return packages.sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
}

function rustPackages() {
  const meta = JSON.parse(
    execFileSync("cargo", ["metadata", "--format-version", "1", "--locked"], { cwd: join(ROOT, "src-tauri"), encoding: "utf8", maxBuffer: 256 << 20 }),
  );
  const byId = new Map(meta.packages.map((p) => [p.id, p]));
  const nodes = new Map(meta.resolve.nodes.map((n) => [n.id, n]));
  const root = meta.packages.find((p) => p.name === "terminus").id;
  const seen = new Set();
  const queue = [root];
  while (queue.length) {
    const id = queue.pop();
    if (seen.has(id)) continue;
    seen.add(id);
    for (const dep of nodes.get(id)?.deps ?? []) {
      if (dep.dep_kinds.some((k) => k.kind === null)) queue.push(dep.pkg);
    }
  }
  return [...seen]
    .map((id) => byId.get(id))
    .filter((p) => p.source)
    .map((p) => ({ name: p.name, version: p.version, license: p.license ?? "", source: p.repository ?? "", texts: licenseTexts(dirname(p.manifest_path)) }))
    .sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
}

mkdirSync(OUT, { recursive: true });
const npm = npmPackages();
writeFileSync(join(OUT, "npm.md"), render("npm dependencies", "Production npm packages bundled into the window's front.", npm));
const rust = rustPackages();
writeFileSync(join(OUT, "rust.md"), render("Rust dependencies", "Crates compiled into the `terminus` executable on any supported platform.", rust));
console.log(`third-party/npm.md: ${npm.length} packages · third-party/rust.md: ${rust.length} crates`);
